{% set version = '0.2.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scclust/scclust_{{ version }}.tar.gz
  sha256: fbb22632b3544d5ee130f077a0d51639ea289793b62ceafddf446a320fd71a09

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-distances
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-distances

test:
  commands:
    - $R -e "library('scclust')"           # [not win]
    - "\"%R%\" -e \"library('scclust')\""  # [win]

about:
  home: https://github.com/fsavje/scclust-R
  license: GPL-3.0-or-later
  summary: Provides wrappers for 'scclust', a C library for computationally efficient size-constrained
    clustering with near-optimal performance. See <https://github.com/fsavje/scclust>
    for more information.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: scclust
# Type: Package
# Title: Size-Constrained Clustering
# Version: 0.2.5
# Date: 2024-07-31
# Authors@R: c( person("Fredrik", "Savje", email = "rpackages@fredriksavje.com", role = c("aut", "cre")), person("Michael", "Higgins", role = "aut"), person("Jasjeet", "Sekhon", role = "aut"))
# Description: Provides wrappers for 'scclust', a C library for computationally efficient size-constrained clustering with near-optimal performance. See <https://github.com/fsavje/scclust> for more information.
# Depends: R (>= 3.4.0), distances
# Imports:
# Suggests: testthat
# NeedsCompilation: yes
# License: GPL (>= 3)
# LicenseNote: The scclust package includes the scclust C library (distributed under the LGPLv2.1 license).
# URL: https://github.com/fsavje/scclust-R
# BugReports: https://github.com/fsavje/scclust-R/issues
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Packaged: 2024-07-31 16:11:53 UTC; fredriksavje
# Author: Fredrik Savje [aut, cre], Michael Higgins [aut], Jasjeet Sekhon [aut]
# Maintainer: Fredrik Savje <rpackages@fredriksavje.com>
# Repository: CRAN
# Date/Publication: 2024-07-31 22:40:02 UTC
